import { Project, Certificate, SkillItem, ServiceItem, UserSettings, SiteContent } from './types';

export const initialProjects: Project[] = [
  {
    id: 'R3GilTqRbXxxo3cY1rIY',
    title: 'mebelmashhura.uz',
    slug: 'mebelmashhura-uz',
    description: "Mebel Do'koni uchun zamonaviy Web sayt va interaktiv katalog",
    desc: "Mebel Do'koni uchun Web sayt",
    longDescription: "mebelmashhura.uz — zamonaviy mebel do'koni uchun yaratilgan qulay, chiroyli va yuqori tezlikda ishlovchi elektron tijorat katalog veb-sayti. Foydalanuvchilar mahsulotlarni qidirish, filtrlar bo'yicha saralash va buyurtma berish imkoniyatiga ega.",
    techStack: ['Next.js', 'React', 'Tailwind CSS', 'TypeScript', 'Responsive Design'],
    coverImageUrl: 'https://i.ibb.co/HL9S5dv4/Screenshot-2026-03-29-114200.png',
    image: 'https://i.ibb.co/HL9S5dv4/Screenshot-2026-03-29-114200.png',
    liveUrl: 'https://mebelmashhura.uz',
    link: 'https://mebelmashhura.uz',
    githubUrl: '',
    category: 'Web Ilova',
    tag: 'Web Ilova',
    color: 'bg-[#f5f5f7]',
    featured: true,
    order: 1,
    challenges: [
      "Mebel kataloglarining yuqori aniqlikdagi rasmlarini tezkor yuklanishini ta'minlash.",
      "Mobil qurilmalar uchun mukammal moslashuvchan (responsive) qulay interfeys yaratish."
    ],
    outcomes: [
      "Sayt yuklanish tezligi 1 soniyadan kam vaqtni tashkil etdi.",
      "Mijozlarning mahsulot tanlash va buyurtma berish jarayoni 40% ga tezlashdi."
    ],
    role: 'Full Stack Dasturchi',
    createdAt: '2026-03-29T06:42:20Z',
  },
  {
    id: 'Y8JFOjmI5oHUKuG46Die',
    title: '3D EARTH',
    slug: '3d-earth',
    description: "Yer sayyorasining Three.js va WebGL asosidagi 3D interaktiv maketi",
    desc: "Yerning 3D maketi",
    longDescription: "Yer sharining 3D interaktiv modeli Three.js va WebGL texnologiyalari asosida yaratilgan. Foydalanuvchi kamerani harakatlantirishi, yerni 360 gradusga aylantirishi, real vaqt rejimidagi atmosferik yorug'lik va soyalar effektini tomosha qilishi mumkin.",
    techStack: ['Three.js', 'WebGL', 'JavaScript', 'HTML5 Canvas', 'CSS3'],
    coverImageUrl: 'https://i.ibb.co/mFMjVnk5/Screenshot-2026-03-30-073653.png',
    image: 'https://i.ibb.co/mFMjVnk5/Screenshot-2026-03-30-073653.png',
    liveUrl: 'https://sanjarbek404.github.io/3d-earth/',
    link: 'https://sanjarbek404.github.io/3d-earth/',
    githubUrl: 'https://github.com/sanjarbek404/3d-earth.git',
    category: '3D Web Ilova',
    tag: 'Web ilova',
    color: 'bg-[#f5f5f7]',
    featured: true,
    order: 2,
    challenges: [
      "Brauzerda 60 FPS silliq aylanish va yuqori sifatli Yer teksturalarini kadr yo'qotishlarsiz render qilish.",
      "Turli quvvatdagi qurilmalarda GPU va xotira sarfini muvozanatlash."
    ],
    outcomes: [
      "GPU apparat tezlanishi orqali barcha qurilmalarda 60 FPS barqaror ko'rinish.",
      "Sub-megabayt teksturalarni yuklash orqali yuklanish vaqti sezilarli qisqartirildi."
    ],
    role: '3D Grafika & Frontend Muhandisi',
    createdAt: '2026-03-30T02:37:30Z',
  },
  {
    id: 'eNO4ta7QcreDhofoy0JD',
    title: 'Aura Habit Tracker',
    slug: 'aura-habit-tracker',
    description: "Kunlik foydali odatlarni shakllantirish va kuzatish uchun PWA platformasi",
    desc: "Aura Habit Tracker ilovasi odatlarni shakllantirish PWA platformasi",
    longDescription: "Aura Habit Tracker — foydalanuvchilarga yangi foydali odatlarni shakllantirish va ularni har kuni kuzatib borishda yordam beruvchi zamonaviy Progressive Web App (PWA). Oflayn rejimda ham to'liq ishlaydi va qurilmaga ilova sifatida o'rnatish mumkin.",
    techStack: ['PWA', 'JavaScript', 'LocalStorage', 'Service Worker', 'Tailwind CSS'],
    coverImageUrl: 'https://i.ibb.co/QvKX9Wxr/Gemini-Generated-Image-nsl1rfnsl1rfnsl1.png',
    image: 'https://i.ibb.co/QvKX9Wxr/Gemini-Generated-Image-nsl1rfnsl1rfnsl1.png',
    liveUrl: 'https://sanjarbek404.github.io/HabitTracker/',
    link: 'https://sanjarbek404.github.io/HabitTracker/',
    githubUrl: 'https://github.com/sanjarbek404/HabitTracker.git',
    category: 'PWA Web Ilova',
    tag: 'Web ilova',
    color: 'bg-[#f5f5f7]',
    featured: true,
    order: 3,
    challenges: [
      "Oflayn rejimda ishlash uchun Service Worker kesh mexanizmi va lokal ma'lumotlar sinxronizatsiyasi.",
      "Odatlar ketma-ketligi (streak) va qulay progress vizualizatsiyasini yaratish."
    ],
    outcomes: [
      "Internet tarmog'isiz ham 100% oflayn ishlash qobiliyati.",
      "Mobil va kompyuterlarga PWA sifatida bir zumda o'rnatilish imkoniyati."
    ],
    role: 'Frontend & PWA Developer',
    createdAt: '2026-03-29T14:05:25Z',
  },
];

export const initialCertificates: Certificate[] = [
  {
    id: '6HY5pJ9DWaN21ssNS9db',
    title: 'Meta Frontend Developer',
    issuer: 'Meta',
    year: '2026',
    dateIssued: '2026',
    image: 'https://i.ibb.co/Txq102hn/Screenshot-2026-04-16-114509.png',
    imageUrl: 'https://i.ibb.co/Txq102hn/Screenshot-2026-04-16-114509.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/C54O8ZTSKJIQ?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/C54O8ZTSKJIQ?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    skills: ['React', 'JavaScript', 'HTML5', 'CSS3', 'Version Control', 'UI/UX'],
    createdAt: '2026-04-16T11:45:09Z',
  },
  {
    id: 'ZouP4vcVcBF1tjrCUIuW',
    title: 'Meta Full Stack Developer: Front-End & Back-End from Scratch',
    issuer: 'Meta',
    year: '2026',
    dateIssued: '2026',
    image: 'https://i.ibb.co/bjGbFJ22/Screenshot-2026-04-26-134653.png',
    imageUrl: 'https://i.ibb.co/bjGbFJ22/Screenshot-2026-04-26-134653.png',
    link: 'https://coursera.org/verify/specialization/HMSLCW4X6WZ7',
    credentialUrl: 'https://coursera.org/verify/specialization/HMSLCW4X6WZ7',
    skills: ['React', 'Node.js', 'Python', 'Django', 'APIs', 'Databases'],
    createdAt: '2026-04-26T13:46:53Z',
  },
  {
    id: 'R1u63XbEo5rfoMWkVjPE',
    title: 'Google AI',
    issuer: 'Google',
    year: '2026',
    dateIssued: '2026',
    image: 'https://i.ibb.co/WNrPwr4g/Screenshot-2026-04-26-134421.png',
    imageUrl: 'https://i.ibb.co/WNrPwr4g/Screenshot-2026-04-26-134421.png',
    link: 'https://coursera.org/verify/professional-cert/FLHNOQPCAX7V',
    credentialUrl: 'https://coursera.org/verify/professional-cert/FLHNOQPCAX7V',
    skills: ['Artificial Intelligence', 'Generative AI', 'Prompt Engineering', 'Machine Learning'],
    createdAt: '2026-04-26T13:44:21Z',
  },
  {
    id: 'BNaJPqcLYvrHmiseSg65',
    title: 'Certified Ethical Hacker',
    issuer: 'Pearson',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/9HryvfXY/Screenshot-2026-05-18-214427.png',
    imageUrl: 'https://i.ibb.co/9HryvfXY/Screenshot-2026-05-18-214427.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/9IMPH143RVW1?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/9IMPH143RVW1?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    skills: ['Network Security', 'Penetration Testing', 'Security Assessment'],
    createdAt: '2025-05-18T21:44:27Z',
  },
  {
    id: 'wxSJtSQgbKBXtWWnKTXn',
    title: 'Google Prompting Essentials',
    issuer: 'GOOGLE',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/VW8rWNkX/Screenshot-2026-05-18-215050.png',
    imageUrl: 'https://i.ibb.co/VW8rWNkX/Screenshot-2026-05-18-215050.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/1U0E3OMLWJWR',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/1U0E3OMLWJWR',
    skills: ['Prompt Engineering', 'Generative AI', 'LLM Workflow Optimization'],
    createdAt: '2025-05-18T21:50:50Z',
  },
  {
    id: 'F3NuPgab8Tn6YeonaMm4',
    title: 'Git and GitHub Complete Master Class',
    issuer: 'Packt',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/s9fJXGjk/Screenshot-2026-05-18-220304.png',
    imageUrl: 'https://i.ibb.co/s9fJXGjk/Screenshot-2026-05-18-220304.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/3B0CS1JKDHU2?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/3B0CS1JKDHU2?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    skills: ['Git', 'GitHub Actions', 'Version Control', 'CI/CD Pipelines'],
    createdAt: '2025-05-18T22:03:04Z',
  },
  {
    id: 'pO8ptuHTYSmaqGTN0IF8',
    title: 'JavaScript from Beginner to Expert 2.0',
    issuer: 'Packt',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/20fd16C0/Screenshot-2026-05-18-220121.png',
    imageUrl: 'https://i.ibb.co/20fd16C0/Screenshot-2026-05-18-220121.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/KQ31TMD7P02Q?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/KQ31TMD7P02Q?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    skills: ['Modern JavaScript', 'ES6+', 'Asynchronous Programming', 'DOM'],
    createdAt: '2025-05-18T22:01:21Z',
  },
  {
    id: 'pcXVxGth5GEsspILR4Q6',
    title: 'CompTIA IT Fundamentals',
    issuer: 'Coursera',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/hFzGBdXb/Screenshot-2026-05-18-215853.png',
    imageUrl: 'https://i.ibb.co/hFzGBdXb/Screenshot-2026-05-18-215853.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/4J1E2B489XZM?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/4J1E2B489XZM?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    skills: ['IT Infrastructure', 'Operating Systems', 'Security Fundamentals'],
    createdAt: '2025-05-18T21:58:53Z',
  },
  {
    id: 'JtRWntjibrrD1dC3LpFx',
    title: 'Cybersecurity in modern organizations',
    issuer: 'Coursera',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/5hrz6nZf/Screenshot-2026-05-18-215217.png',
    imageUrl: 'https://i.ibb.co/5hrz6nZf/Screenshot-2026-05-18-215217.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/XS5P97I39JMV?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/XS5P97I39JMV?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    skills: ['Organizational Security', 'Threat Analysis', 'Cyber Defense'],
    createdAt: '2025-05-18T21:52:17Z',
  },
  {
    id: 'xsE5ag4ulUTknwvQvrxD',
    title: 'Cyber Security: Leadership',
    issuer: 'Coursera',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/DPd1R0CK/Screenshot-2026-05-18-214804.png',
    imageUrl: 'https://i.ibb.co/DPd1R0CK/Screenshot-2026-05-18-214804.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/2SOJVQULTEE8',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/2SOJVQULTEE8',
    skills: ['Security Leadership', 'Governance', 'Risk Management'],
    createdAt: '2025-05-18T21:48:04Z',
  },
  {
    id: 'jous05yxh272t3zxUPPX',
    title: 'Learn English: Beginning Grammar',
    issuer: 'UC Irvine',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/1tY8MkbP/Screenshot-2026-05-18-215418.png',
    imageUrl: 'https://i.ibb.co/1tY8MkbP/Screenshot-2026-05-18-215418.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/3MC10AFSQ0NK?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/3MC10AFSQ0NK?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    skills: ['English Grammar', 'Professional Communication'],
    createdAt: '2025-05-18T21:54:18Z',
  },
];

export const initialSkills: SkillItem[] = [
  {
    id: 'Igu7jXFDW5XzsVuyJ55p',
    name: 'Javascript',
    level: 95,
    category: 'Frontend',
    iconUrl: 'https://cdn.simpleicons.org/javascript',
    iconName: 'FileCode',
  },
  {
    id: '7inamiiF63O4tpWYGdTP',
    name: 'HTML5',
    level: 85,
    category: 'Frontend',
    iconUrl: 'https://cdn.simpleicons.org/html5',
    iconName: 'Globe',
  },
  {
    id: 'LhPC1yCjOPi2D7cJJgzx',
    name: 'Node JS',
    level: 79,
    category: 'Backend',
    iconUrl: 'https://cdn.simpleicons.org/nodedotjs',
    iconName: 'Server',
  },
  {
    id: 'pzfuDp3HbgZFaiOUQPzQ',
    name: 'Tailwind CSS',
    level: 76,
    category: 'Frontend',
    iconUrl: 'https://cdn.simpleicons.org/tailwindcss',
    iconName: 'Palette',
  },
  {
    id: '6SdMA3XT0vyrVHIsVS5X',
    name: 'Firebase',
    level: 75,
    category: 'Database',
    iconUrl: 'https://cdn.simpleicons.org/firebase',
    iconName: 'Flame',
  },
  {
    id: 'q2D2mmuA5ECw5Vxaa5bP',
    name: 'Python',
    level: 70,
    category: 'Backend',
    iconUrl: 'https://cdn.simpleicons.org/python',
    iconName: 'Terminal',
  },
  {
    id: 'frz5qFYPX6jPjOLdygkk',
    name: 'React',
    level: 55,
    category: 'Frontend',
    iconUrl: 'https://cdn.simpleicons.org/react',
    iconName: 'Code2',
  },
  {
    id: 'Kj8L9wJuZYgL24zUlCN6',
    name: 'Git',
    level: 50,
    category: 'DevOps & Tools',
    iconUrl: 'https://cdn.simpleicons.org/git',
    iconName: 'GitBranch',
  },
  {
    id: 'S5o22lzsa5bk4l0M8OtK',
    name: 'Figma',
    level: 50,
    category: 'Design & Other',
    iconUrl: 'https://cdn.simpleicons.org/figma',
    iconName: 'Sparkles',
  },
  {
    id: 'xbQrjdyJWtwpjHeN5tnh',
    name: 'MySQL',
    level: 50,
    category: 'Database',
    iconUrl: 'https://cdn.simpleicons.org/mysql',
    iconName: 'Database',
  },
  {
    id: 'PROX6z8Heb95BgKR3Y3q',
    name: 'Mongo DB',
    level: 40,
    category: 'Database',
    iconUrl: 'https://cdn.simpleicons.org/mongodb',
    iconName: 'HardDrive',
  },
];

export const initialServices: ServiceItem[] = [
  {
    id: 'RrgOy6Bi0PLBFy3ZemhE',
    title: 'Telegram Bot',
    desc: 'Marketingni va biznes jarayonlarini avtomatlashtiruvchi, to\'lov tizimlari ulangan professional Telegram botlar.',
    priceRange: '150$ – 1500$',
    icon: 'Bot',
  },
  {
    id: 'uyS4ME3JcrrhBdRpA7vw',
    title: 'Landing Pagelar',
    desc: 'Sotuv do\'koni, brendlar yoki marketplace uchun yuqori konversiyali, tezkor va zamonaviy veb sahifalar.',
    priceRange: '20$ – 300$',
    icon: 'Code',
  },
];

export const initialSettings: UserSettings = {
  github: 'https://github.com/sanjarbek404',
  telegram: 'https://t.me/sanjarbek_404',
  linkedin: 'https://www.linkedin.com/in/sanjarbek-otabekov-0600733bb/',
  email: 'sanjarbekotabekov010@gmail.com',
  resume: '/resume.pdf',
  aboutTitle: 'Men Haqimda',
  aboutShort: 'Zamonaviy veb-arxitektura va yuqori tezlikdagi raqamli mahsulotlar yaratishga ixtisoslashgan Full Stack muhandisman. Murakkab vazifalarga toza kod, ilg\'or texnologiyalar va intuitiv interfeyslar orqali qulay yechim topaman.',
  aboutFull: 'Mening maqsadim — har bir loyihada yuqori yuklanish tezligi, xavfsizlik va mukammal foydalanuvchi tajribasini (UX) ta\'minlash. Next.js, TypeScript va zamonaviy texnologiyalar bilan bizneslar uchun aniq natija beruvchi yechimlar yarataman.',
  expYears: '1+',
  githubCommits: '110+',
  githubYearText: 'Bu yilgi faollik',
  spotifySong: 'Lofi Programming Coding Playlist',
  spotifyArtist: 'Coding Playlist',
  instagram: '',
};

export const initialSiteContent: SiteContent = {
  hero: {
    name: 'Sanjarbek Otabekov',
    role: 'Full Stack Dasturchi',
    tagline: 'Tezkor, xavfsiz va zamonaviy raqamli tizimlar arxitekturasi',
    subtext: 'Next.js, TypeScript va zamonaviy veb texnologiyalar yordamida biznes va foydalanuvchilar uchun yuqori samaradorlikka ega raqamli mahsulotlar yarataman.',
    availabilityStatus: 'Loyihalar va frilans uchun ochiq',
    primaryCtaText: 'Loyihalarni ko‘rish',
    secondaryCtaText: 'Bog‘lanish',
    avatarUrl: '/images/personaj-sanjarbek.webp',
  },
  about: {
    heading: initialSettings.aboutTitle,
    bioParagraphs: [
      initialSettings.aboutShort,
      initialSettings.aboutFull
    ],
    yearsExperience: 1,
    projectsCompleted: 15,
    happyClients: 12,
    codeQualityRate: '99.9%',
    location: 'Toshkent, O‘zbekiston (Masofaviy ishga tayyor)',
    availability: 'Frilans & To‘liq bandlik',
    languages: ['O‘zbek tili (Ona tili)', 'Ingliz tili (Texnik/B2)', 'Rus tili (Muloqot)'],
    githubCommits: initialSettings.githubCommits,
    spotifySong: initialSettings.spotifySong,
    spotifyArtist: initialSettings.spotifyArtist,
  },
  skills: initialSkills,
  services: initialServices,
  settings: initialSettings,
};
