import { Project, Certificate, SkillItem, ServiceItem, UserSettings, SiteContent, MilestoneItem, TestimonialItem } from './types';

export const initialProjects: Project[] = [
  {
    id: 'R3GilTqRbXxxo3cY1rIY',
    title: 'mebelmashhura.uz',
    slug: 'mebelmashhura-uz',
    description: "Mebel do'koni uchun yaratilgan zamonaviy elektron tijorat katalogi va buyurtma platformasi.",
    desc: "Mebel do'koni veb-sayti va katalogi",
    longDescription: "mebelmashhura.uz — zamonaviy mebel do'koni uchun yaratilgan qulay, chiroyli va yuqori tezlikda ishlovchi elektron tijorat katalog veb-sayti. Foydalanuvchilar mahsulotlarni qidirish, filtrlar bo'yicha saralash va buyurtma berish imkoniyatiga ega.",
    techStack: ['Next.js', 'React', 'Tailwind CSS', 'TypeScript', 'Responsive Design'],
    coverImageUrl: 'https://i.ibb.co/HL9S5dv4/Screenshot-2026-03-29-114200.png',
    image: 'https://i.ibb.co/HL9S5dv4/Screenshot-2026-03-29-114200.png',
    liveUrl: 'https://mebelmashhura.uz',
    link: 'https://mebelmashhura.uz',
    githubUrl: 'https://github.com/sanjarbek0828/mebelmashhura.uz',
    category: 'E-Commerce',
    tag: 'E-Commerce',
    color: 'bg-[#f5f5f7]',
    featured: true,
    order: 1,
    challenges: [
      "Mebel kataloglarining yuqori aniqlikdagi rasmlarini tezkor yuklanishini ta'minlash.",
      "Mobil qurilmalar uchun mukammal moslashuvchan (responsive) qulay interfeys yaratish."
    ],
    outcomes: [
      "Sayt yuklanish tezligi 1 soniyadan kam vaqtni tashkil etdi.",
      "Mijozlarning mahsulot tanlash va buyurtma berish jarayoni 40% ga tezlashdi."
    ],
    role: 'Full Stack Dasturchi',
    createdAt: '2026-03-29T06:42:20Z',
  },
  {
    id: 'finalytix-ai-dashboard',
    title: 'FINALYTIX — AI Expense Analyzer',
    slug: 'finalytix-ai-dashboard',
    description: "Google Gemini API NLP integratsiyalangan aqlli moliya va xarajatlar tahlili boshqaruv paneli.",
    desc: "AI moliya va xarajatlar tahlilchisi",
    longDescription: "FINALYTIX — bu sun'iy intellekt (Google Gemini API) asosida ishlovchi aqlli moliyaviy yordamchi platforma. Foydalanuvchi tabiiy tilda yozgan xarajatlarini (O'zbek, Rus, Ingliz) tizim avtomatik tushunadi, kategoriyalar va valyutani ajratib, Recharts interaktiv grafiklarida vizual hisobotlar yaratadi.",
    techStack: ['React 19', 'TypeScript', 'Google Gemini API', 'Tailwind CSS', 'Recharts', 'Vite'],
    coverImageUrl: '/images/projects/finalytix.jpg',
    image: '/images/projects/finalytix.jpg',
    liveUrl: 'https://sanjarbek404.github.io/FINALYTIX-Dashboard/',
    link: 'https://sanjarbek404.github.io/FINALYTIX-Dashboard/',
    githubUrl: 'https://github.com/sanjarbek404/FINALYTIX-Dashboard',
    category: "Sun'iy Intellekt / AI",
    tag: "Sun'iy Intellekt / AI",
    color: 'bg-[#0f172a]',
    featured: true,
    order: 2,
    challenges: [
      "Tabiiy tildagi erkin matnlardan aniq moliyaviy struktura (summa, valyuta, toifa)ni NLP orqali ajratib olish.",
      "Turli xil xalqaro valyutalarni bir zumda konvertatsiya qilish va interaktiv diagrammalarda aks ettirish."
    ],
    outcomes: [
      "Gemini API orqali 99% aniqlikda xarajatlarni avtomatik kategoriyalashga erishildi.",
      "Foydalanuvchi uchun xarajat kiritish jarayoni 10 soniyadan 2 soniyaga tushirildi."
    ],
    role: 'AI & Frontend Engineer',
    createdAt: '2026-06-15T10:00:00Z',
  },
  {
    id: 'Y8JFOjmI5oHUKuG46Die',
    title: '3D Earth WebGL',
    slug: '3d-earth',
    description: "Yer sayyorasining Three.js va WebGL asosidagi 60 FPS silliq interaktiv 3D maketi.",
    desc: "Yer sharining 3D maketi",
    longDescription: "Yer sharining 3D interaktiv modeli Three.js va WebGL texnologiyalari asosida yaratilgan. Foydalanuvchi kamerani harakatlantirishi, yerni 360 gradusga aylantirishi, real vaqt rejimidagi atmosferik yorug'lik va soyalar effektini tomosha qilishi mumkin.",
    techStack: ['Three.js', 'WebGL', 'JavaScript', 'HTML5 Canvas', 'CSS3'],
    coverImageUrl: 'https://i.ibb.co/mFMjVnk5/Screenshot-2026-03-30-073653.png',
    image: 'https://i.ibb.co/mFMjVnk5/Screenshot-2026-03-30-073653.png',
    liveUrl: 'https://sanjarbek404.github.io/3d-earth/',
    link: 'https://sanjarbek404.github.io/3d-earth/',
    githubUrl: 'https://github.com/sanjarbek0828/3d-earth',
    category: '3D Web Ilova',
    tag: '3D Web Ilova',
    color: 'bg-[#050510]',
    featured: true,
    order: 3,
    challenges: [
      "Brauzerda 60 FPS silliq aylanish va yuqori sifatli Yer teksturalarini kadr yo'qotishlarsiz render qilish.",
      "Turli quvvatdagi qurilmalarda GPU va xotira sarfini muvozanatlash."
    ],
    outcomes: [
      "GPU apparat tezlanishi orqali barcha qurilmalarda 60 FPS barqaror ko'rinish.",
      "Sub-megabayt teksturalarni yuklash orqali yuklanish vaqti sezilarli qisqartirildi."
    ],
    role: '3D Grafika & Frontend Muhandisi',
    createdAt: '2026-03-30T02:37:30Z',
  },
  {
    id: 'moviemind-cinema-portal',
    title: 'MovieMind — Kinolar Portali',
    slug: 'moviemind-portal',
    description: "TMDb API bilan integratsiya qilingan, to'liq O'zbek tilidagi kinolar va treylerlar platformasi.",
    desc: "Kinolar va treylerlar qidiruv portali",
    longDescription: "MovieMind — bu eng so'nggi va ommabop kinolarni izlash, batafsil ma'lumotlar, reytinglar, aktyorlar tarkibi va treylerlarni ko'rish imkonini beruvchi zamonaviy web-ilova. To'liq O'zbek tiliga moslashtirilgan interfeys va saralash algoritmlariga ega.",
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'TMDb API', 'Vite'],
    coverImageUrl: '/images/projects/moviemind.jpg',
    image: '/images/projects/moviemind.jpg',
    liveUrl: 'https://sanjarbek404.github.io/Movie-Mind/',
    link: 'https://sanjarbek404.github.io/Movie-Mind/',
    githubUrl: 'https://github.com/sanjarbek404/Movie-Mind',
    category: 'Web Ilova',
    tag: 'Web Ilova',
    color: 'bg-[#09090b]',
    featured: true,
    order: 4,
    challenges: [
      "TMDb API orqali millionlab filmlarni kechikishlarsiz qidirish va kesh mexanizmini yaratish.",
      "Mobil va planshetlarda video treylerlarni to'xtovsiz silliq namoyish etish."
    ],
    outcomes: [
      "Kinofilmlar qidiruvi 150ms ichida natija beruvchi debounced qidiruv bilan ta'minlandi.",
      "Sevimlilar ro'yxati (Favorites) funksiyasi bilan foydalanuvchilar qoniqishi oshirildi."
    ],
    role: 'Frontend Muhandisi',
    createdAt: '2026-05-10T12:00:00Z',
  },
  {
    id: 'taskflow-board-kanban',
    title: 'TaskFlow Board — Kanban Tizimi',
    slug: 'taskflow-board',
    description: "Interaktiv drag-and-drop Kanban vazifalar boshqaruv taxtasi va sprint workflow platformasi.",
    desc: "Kanban vazifalar taxtasi",
    longDescription: "TaskFlow Board — jamoalar va dasturchilar uchun loyihalarni boshqarishga mo'ljallangan yuqori tezlikdagi Kanban taxtasi. @dnd-kit kutubxonasi yordamida vazifalarni ustunlar bo'ylab erkin surish, ustunlarni tahrirlash va LocalStorage bilan avtomatik sinxronlash imkoniyatini beradi.",
    techStack: ['React 19', 'TypeScript', '@dnd-kit/core', 'Tailwind CSS v4', 'Vite'],
    coverImageUrl: '/images/projects/taskflow.jpg',
    image: '/images/projects/taskflow.jpg',
    liveUrl: 'https://sanjarbek404.github.io/TaskFlow-Board/',
    link: 'https://sanjarbek404.github.io/TaskFlow-Board/',
    githubUrl: 'https://github.com/sanjarbek404/TaskFlow-Board',
    category: 'SaaS / Unumdorlik',
    tag: 'SaaS / Unumdorlik',
    color: 'bg-[#0f172a]',
    featured: true,
    order: 5,
    challenges: [
      "Katta hajmdagi vazifalar ro'yxatini qayta tartiblashda (reorder) minimal qayta renderlashni ta'minlash.",
      "Sensorda va sichqonchada bir xil darajada sezgir drag-and-drop mexanizmini o'rnatish."
    ],
    outcomes: [
      "dnd-kit sensorlari orqali 60 FPS darajasida qulay va silliq surish tajribasi.",
      "To'liq oflayn ishlovchi brauzer xotirasi bilan uzluksiz ma'lumotlar saqlanishi."
    ],
    role: 'Lead Frontend Dasturchi',
    createdAt: '2026-05-20T14:30:00Z',
  },
  {
    id: 'palitra-pro-generator',
    title: 'Palitra Pro — Rang Generator',
    slug: 'palitra-pro',
    description: "Dizaynerlar va dasturchilar uchun zamonaviy ranglar uyg'unligi generatsiyasi va kod eksporti vositasi.",
    desc: "Professional ranglar palitrasi vositasi",
    longDescription: "Palitra Pro — Monochromatic, Analogous, Triadic kabi ilmiy rang uyg'unligi qoidalari asosida yangi palitralar generatsiya qiluvchi zamonaviy dastur. Ranglarni HEX, RGB, HSL formatlarida nusxalash va Tailwind CSS hamda CSS Variables qilib to'g'ridan-to'g'ri eksport qilish imkoniyati mavjud.",
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'Color Theory'],
    coverImageUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    liveUrl: 'https://sanjarbek404.github.io/Palitra-Pro/',
    link: 'https://sanjarbek404.github.io/Palitra-Pro/',
    githubUrl: 'https://github.com/sanjarbek404/Palitra-Pro',
    category: 'Dizayn Asbobi',
    tag: 'Dizayn Asbobi',
    color: 'bg-[#18181b]',
    featured: false,
    order: 6,
    challenges: [
      "Ranglarning kontrast koeffitsientini hisoblash va WCAG talablariga mos ko'rinish yaratish.",
      "Klaviatura yordamida (Space, Lock/Unlock) tezkor boshqaruvni yo'lga qo'yish."
    ],
    outcomes: [
      "Dizaynerlar va dasturchilar uchun tayyor CSS/Tailwind ranglar konfiguratsiyasini bir soniyada olish imkoni.",
      "Tezkor klavishlar orqali generatsiya tezligi 3 barobarga oshirildi."
    ],
    role: 'UI/UX & Frontend Developer',
    createdAt: '2026-06-01T09:15:00Z',
  },
  {
    id: 'protasker-editorial',
    title: 'ProTasker — Editorial To-Do',
    slug: 'protasker-editorial',
    description: "Klassik editorial dizayn, kalendar integratsiyasi va Framer Motion animatsiyalariga ega to-do tizimi.",
    desc: "Editorial vazifalar boshqaruvchisi",
    longDescription: "ProTasker — yuqori did bilan ishlangan 'Editorial Aesthetic' dizayndagi zamonaviy vazifalar menejeri. Kalendar ko'rinishi, ustuvorlik darajalari (past, o'rta, yuqori), toifalar va silliq interaktiv animatsiyalar bilan ta'minlangan.",
    techStack: ['React', 'TypeScript', 'Framer Motion', 'Tailwind CSS', 'Vite'],
    coverImageUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=1200&q=80',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=1200&q=80',
    liveUrl: 'https://sanjarbek404.github.io/protasker/',
    link: 'https://sanjarbek404.github.io/protasker/',
    githubUrl: 'https://github.com/sanjarbek404/protasker',
    category: 'Web Ilova',
    tag: 'Web Ilova',
    color: 'bg-[#fafafa]',
    featured: false,
    order: 7,
    challenges: [
      "Tipografik estetika va qulay interaktiv vazifalar boshqaruvi o'rtasidagi muvozanat.",
      "Framer Motion layout animatsiyalari bilan ro'yxat tartibini buzmasdan yangilash."
    ],
    outcomes: [
      "Minimalist qora-oq interfeys yordamida diqqatni faqat muhim vazifalarga qaratish imkoni.",
      "100% oflayn xotira bilan doimiy ma'lumotlar saqlanishi."
    ],
    role: 'Frontend Dasturchi',
    createdAt: '2026-06-10T16:00:00Z',
  },
  {
    id: 'eNO4ta7QcreDhofoy0JD',
    title: 'Aura Habit Tracker',
    slug: 'aura-habit-tracker',
    description: "Kunlik foydali odatlarni shakllantirish va kuzatish uchun PWA platformasi.",
    desc: "Odatlarni shakllantirish PWA platformasi",
    longDescription: "Aura Habit Tracker — foydalanuvchilarga yangi foydali odatlarni shakllantirish va ularni har kuni kuzatib borishda yordam beruvchi zamonaviy Progressive Web App (PWA). Oflayn rejimda ham to'liq ishlaydi va qurilmaga ilova sifatida o'rnatish mumkin.",
    techStack: ['PWA', 'JavaScript', 'LocalStorage', 'Service Worker', 'Tailwind CSS'],
    coverImageUrl: 'https://i.ibb.co/QvKX9Wxr/Gemini-Generated-Image-nsl1rfnsl1rfnsl1.png',
    image: 'https://i.ibb.co/QvKX9Wxr/Gemini-Generated-Image-nsl1rfnsl1rfnsl1.png',
    liveUrl: 'https://sanjarbek404.github.io/HabitTracker/',
    link: 'https://sanjarbek404.github.io/HabitTracker/',
    githubUrl: 'https://github.com/sanjarbek0828/flowtask',
    category: 'PWA Web Ilova',
    tag: 'PWA Web Ilova',
    color: 'bg-[#f5f5f7]',
    featured: false,
    order: 8,
    challenges: [
      "Oflayn rejimda ishlash uchun Service Worker kesh mexanizmi va lokal ma'lumotlar sinxronizatsiyasi.",
      "Odatlar ketma-ketligi (streak) va qulay progress vizualizatsiyasini yaratish."
    ],
    outcomes: [
      "Internet tarmog'isiz ham 100% oflayn ishlash qobiliyati.",
      "Mobil va kompyuterlarga PWA sifatida bir zumda o'rnatilish imkoniyati."
    ],
    role: 'Frontend & PWA Developer',
    createdAt: '2026-03-29T14:05:25Z',
  },
  {
    id: 'ultra-ping-game',
    title: 'Ultra Ping — Cyberpunk Arcade',
    slug: 'ultra-ping',
    description: "Geometric Balance dizayn uslubidagi 60+ FPS HTML5 Canvas va sun'iy ong (AI) raqibli Ping Pong o'yini.",
    desc: "Kiberpank Ping Pong o'yini",
    longDescription: "Ultra Ping — kiberpank va neon detallariga boy, yuqori kadrlar chastotasiga ega zamonaviy Ping Pong o'yini. To'g'ridan-to'g'ri requestAnimationFrame va Canvas yordamida ishlovchi Game Loop, AI raqib va zarrachalar (particles) effektlari bilan qurollangan.",
    techStack: ['React', 'TypeScript', 'HTML5 Canvas', 'Game Loop', 'Tailwind CSS'],
    coverImageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80',
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80',
    liveUrl: 'https://sanjarbek404.github.io/Ultra-Ping/',
    link: 'https://sanjarbek404.github.io/Ultra-Ping/',
    githubUrl: 'https://github.com/sanjarbek404/Ultra-Ping',
    category: "Geymdev / Web O'yin",
    tag: "Geymdev / Web O'yin",
    color: 'bg-[#030712]',
    featured: false,
    order: 9,
    challenges: [
      "React re-renderlaridan mustaqil 60 FPS o'yin siklini yaratish.",
      "AI raqibning harakatlanish logikasini inson reflekslariga yaqinlashtirish."
    ],
    outcomes: [
      "Barcha ekran o'lchamlari va kadr chastotalarida bir tekis harakatlanuvchi silliq fizika.",
      "O'yin zavqini oshiruvchi ekran silkinishi va zarracha effektlari."
    ],
    role: 'Gamedev & Web Muhandisi',
    createdAt: '2026-06-25T17:00:00Z',
  },
  {
    id: 'breakout-2d-game',
    title: '2D Breakout Arcade',
    slug: '2d-breakout-arcade',
    description: "Noldan qurilgan to'qnashuvlar fizikasi, Web Audio API va Arkanoid arxitekturasiga ega klassik o'yin.",
    desc: "Klassik Breakout arkanoid o'yini",
    longDescription: "2D Breakout Game — HTML5 Canvas va TypeScript yordamida hech qanday og'ir tashqi geym-dvijoklarsiz (masalan, Phaser) sof matematik fizika bilan qurilgan o'yin. Doira-to'rtburchak to'qnashuv algoritmlari, Web Audio API orqali generatsiya qilinadigan ovozlar va bosqichma-bosqich murakkablashuvchi darajalar mavjud.",
    techStack: ['TypeScript', 'HTML5 Canvas', 'Web Audio API', 'Tailwind CSS', 'Vite'],
    coverImageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
    liveUrl: 'https://sanjarbek404.github.io/-2D-Breakout-Game/',
    link: 'https://sanjarbek404.github.io/-2D-Breakout-Game/',
    githubUrl: 'https://github.com/sanjarbek0828/-2D-Breakout-Game',
    category: "Geymdev / Web O'yin",
    tag: "Geymdev / Web O'yin",
    color: 'bg-[#0f172a]',
    featured: false,
    order: 10,
    challenges: [
      "To'p va raketka orasidagi zarba burchagini to'qnashuv nuqtasiga qarab dinamik o'zgartirish fizikasi.",
      "Tashqi audio fayllarsiz Web Audio API osillyatorlari orqali retro 8-bit tovushlarni yaratish."
    ],
    outcomes: [
      "Nol kechikish va yuqori unumdorlikka ega 60 FPS o'yin jarayoni.",
      "Kross-brauzer barqaror fizik hisob-kitoblar."
    ],
    role: 'TypeScript & Canvas Engineer',
    createdAt: '2026-07-01T11:20:00Z',
  },
  {
    id: 'travel-planner-app',
    title: 'Sayohat Rejalashtiruvchi',
    slug: 'travel-planner',
    description: "OpenStreetMap (Leaflet.js) xaritasi, shahar qidiruvi va ob-havo ma'lumotlariga ega sayohat tizimi.",
    desc: "Sayohat rejalashtirish va xarita platformasi",
    longDescription: "Sayohat Rejalashtiruvchi — foydalanuvchilarga dunyo bo'ylab bormoqchi bo'lgan manzillarini topish, Leaflet.js xaritasida diqqatga sazovor nuqtalarni ko'rish, real vaqt ob-havosini tekshirish va o'z sayohat jadvalini shakllantirish imkonini beruvchi zamonaviy web platforma.",
    techStack: ['React', 'TypeScript', 'Leaflet.js', 'OpenStreetMap', 'Tailwind CSS', 'Vite'],
    coverImageUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80',
    image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80',
    liveUrl: 'https://sanjarbek404.github.io/Travel/',
    link: 'https://sanjarbek404.github.io/Travel/',
    githubUrl: 'https://github.com/sanjarbek404/Travel',
    category: 'Web Ilova',
    tag: 'Web Ilova',
    color: 'bg-[#0c4a6e]',
    featured: false,
    order: 11,
    challenges: [
      "Nominatim geokodlash API-si orqali shahar nomlarini aniq koordinatalarga o'girish.",
      "Interaktiv Leaflet xaritasini React hayot sikli bilan to'g'ri integratsiya qilish."
    ],
    outcomes: [
      "Foydalanuvchilar bir necha daqiqada to'liq sayohat marshrutini tuzish imkoniyatiga ega bo'ldi.",
      "Ob-havo va xarita bitta interfeysda jamlanib, qulaylik sezilarli oshirildi."
    ],
    role: 'Frontend Dasturchi',
    createdAt: '2026-07-08T15:45:00Z',
  },
];

export const initialCertificates: Certificate[] = [
  {
    id: '6HY5pJ9DWaN21ssNS9db',
    title: 'Meta Frontend Developer',
    issuer: 'Meta',
    year: '2026',
    dateIssued: '2026',
    image: 'https://i.ibb.co/Txq102hn/Screenshot-2026-04-16-114509.png',
    imageUrl: 'https://i.ibb.co/Txq102hn/Screenshot-2026-04-16-114509.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/C54O8ZTSKJIQ?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/C54O8ZTSKJIQ?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    skills: ['React', 'JavaScript', 'HTML5', 'CSS3', 'Version Control', 'UI/UX'],
    createdAt: '2026-04-16T11:45:09Z',
  },
  {
    id: 'ZouP4vcVcBF1tjrCUIuW',
    title: 'Meta Full Stack Developer: Front-End & Back-End from Scratch',
    issuer: 'Meta',
    year: '2026',
    dateIssued: '2026',
    image: 'https://i.ibb.co/bjGbFJ22/Screenshot-2026-04-26-134653.png',
    imageUrl: 'https://i.ibb.co/bjGbFJ22/Screenshot-2026-04-26-134653.png',
    link: 'https://coursera.org/verify/specialization/HMSLCW4X6WZ7',
    credentialUrl: 'https://coursera.org/verify/specialization/HMSLCW4X6WZ7',
    skills: ['React', 'Node.js', 'Python', 'Django', 'APIs', 'Databases'],
    createdAt: '2026-04-26T13:46:53Z',
  },
  {
    id: 'R1u63XbEo5rfoMWkVjPE',
    title: 'Google AI',
    issuer: 'Google',
    year: '2026',
    dateIssued: '2026',
    image: 'https://i.ibb.co/WNrPwr4g/Screenshot-2026-04-26-134421.png',
    imageUrl: 'https://i.ibb.co/WNrPwr4g/Screenshot-2026-04-26-134421.png',
    link: 'https://coursera.org/verify/professional-cert/FLHNOQPCAX7V',
    credentialUrl: 'https://coursera.org/verify/professional-cert/FLHNOQPCAX7V',
    skills: ['Artificial Intelligence', 'Generative AI', 'Prompt Engineering', 'Machine Learning'],
    createdAt: '2026-04-26T13:44:21Z',
  },
  {
    id: 'BNaJPqcLYvrHmiseSg65',
    title: 'Certified Ethical Hacker',
    issuer: 'Pearson',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/9HryvfXY/Screenshot-2026-05-18-214427.png',
    imageUrl: 'https://i.ibb.co/9HryvfXY/Screenshot-2026-05-18-214427.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/9IMPH143RVW1?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/9IMPH143RVW1?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    skills: ['Network Security', 'Penetration Testing', 'Security Assessment'],
    createdAt: '2025-05-18T21:44:27Z',
  },
  {
    id: 'wxSJtSQgbKBXtWWnKTXn',
    title: 'Google Prompting Essentials',
    issuer: 'GOOGLE',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/VW8rWNkX/Screenshot-2026-05-18-215050.png',
    imageUrl: 'https://i.ibb.co/VW8rWNkX/Screenshot-2026-05-18-215050.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/1U0E3OMLWJWR',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/1U0E3OMLWJWR',
    skills: ['Prompt Engineering', 'Generative AI', 'LLM Workflow Optimization'],
    createdAt: '2025-05-18T21:50:50Z',
  },
  {
    id: 'F3NuPgab8Tn6YeonaMm4',
    title: 'Git and GitHub Complete Master Class',
    issuer: 'Packt',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/s9fJXGjk/Screenshot-2026-05-18-220304.png',
    imageUrl: 'https://i.ibb.co/s9fJXGjk/Screenshot-2026-05-18-220304.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/3B0CS1JKDHU2?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/3B0CS1JKDHU2?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    skills: ['Git', 'GitHub Actions', 'Version Control', 'CI/CD Pipelines'],
    createdAt: '2025-05-18T22:03:04Z',
  },
  {
    id: 'pO8ptuHTYSmaqGTN0IF8',
    title: 'JavaScript from Beginner to Expert 2.0',
    issuer: 'Packt',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/20fd16C0/Screenshot-2026-05-18-220121.png',
    imageUrl: 'https://i.ibb.co/20fd16C0/Screenshot-2026-05-18-220121.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/KQ31TMD7P02Q?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/KQ31TMD7P02Q?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    skills: ['Modern JavaScript', 'ES6+', 'Asynchronous Programming', 'DOM'],
    createdAt: '2025-05-18T22:01:21Z',
  },
  {
    id: 'pcXVxGth5GEsspILR4Q6',
    title: 'CompTIA IT Fundamentals',
    issuer: 'Coursera',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/hFzGBdXb/Screenshot-2026-05-18-215853.png',
    imageUrl: 'https://i.ibb.co/hFzGBdXb/Screenshot-2026-05-18-215853.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/4J1E2B489XZM?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/4J1E2B489XZM?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    skills: ['IT Infrastructure', 'Operating Systems', 'Security Fundamentals'],
    createdAt: '2025-05-18T21:58:53Z',
  },
  {
    id: 'JtRWntjibrrD1dC3LpFx',
    title: 'Cybersecurity in modern organizations',
    issuer: 'Coursera',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/5hrz6nZf/Screenshot-2026-05-18-215217.png',
    imageUrl: 'https://i.ibb.co/5hrz6nZf/Screenshot-2026-05-18-215217.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/XS5P97I39JMV?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/XS5P97I39JMV?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    skills: ['Organizational Security', 'Threat Analysis', 'Cyber Defense'],
    createdAt: '2025-05-18T21:52:17Z',
  },
  {
    id: 'xsE5ag4ulUTknwvQvrxD',
    title: 'Cyber Security: Leadership',
    issuer: 'Coursera',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/DPd1R0CK/Screenshot-2026-05-18-214804.png',
    imageUrl: 'https://i.ibb.co/DPd1R0CK/Screenshot-2026-05-18-214804.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/2SOJVQULTEE8',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/2SOJVQULTEE8',
    skills: ['Security Leadership', 'Governance', 'Risk Management'],
    createdAt: '2025-05-18T21:48:04Z',
  },
  {
    id: 'jous05yxh272t3zxUPPX',
    title: 'Learn English: Beginning Grammar',
    issuer: 'UC Irvine',
    year: '2025',
    dateIssued: '2025',
    image: 'https://i.ibb.co/1tY8MkbP/Screenshot-2026-05-18-215418.png',
    imageUrl: 'https://i.ibb.co/1tY8MkbP/Screenshot-2026-05-18-215418.png',
    link: 'https://www.coursera.org/account/accomplishments/specialization/3MC10AFSQ0NK?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/3MC10AFSQ0NK?utm_source%3Dandroid%26utm_medium%3Dcertificate%26utm_content%3Dcert_image%26utm_campaign%3Dsharing_cta%26utm_product%3Ds12n',
    skills: ['English Grammar', 'Professional Communication'],
    createdAt: '2025-05-18T21:54:18Z',
  },
];

export const initialSkills: SkillItem[] = [
  {
    id: 'Igu7jXFDW5XzsVuyJ55p',
    name: 'Javascript',
    level: 95,
    category: 'Frontend',
    iconUrl: 'https://cdn.simpleicons.org/javascript',
    iconName: 'FileCode',
  },
  {
    id: '7inamiiF63O4tpWYGdTP',
    name: 'HTML5',
    level: 85,
    category: 'Frontend',
    iconUrl: 'https://cdn.simpleicons.org/html5',
    iconName: 'Globe',
  },
  {
    id: 'LhPC1yCjOPi2D7cJJgzx',
    name: 'Node JS',
    level: 79,
    category: 'Backend',
    iconUrl: 'https://cdn.simpleicons.org/nodedotjs',
    iconName: 'Server',
  },
  {
    id: 'pzfuDp3HbgZFaiOUQPzQ',
    name: 'Tailwind CSS',
    level: 76,
    category: 'Frontend',
    iconUrl: 'https://cdn.simpleicons.org/tailwindcss',
    iconName: 'Palette',
  },
  {
    id: '6SdMA3XT0vyrVHIsVS5X',
    name: 'Firebase',
    level: 75,
    category: 'Database',
    iconUrl: 'https://cdn.simpleicons.org/firebase',
    iconName: 'Flame',
  },
  {
    id: 'q2D2mmuA5ECw5Vxaa5bP',
    name: 'Python',
    level: 70,
    category: 'Backend',
    iconUrl: 'https://cdn.simpleicons.org/python',
    iconName: 'Terminal',
  },
  {
    id: 'frz5qFYPX6jPjOLdygkk',
    name: 'React',
    level: 55,
    category: 'Frontend',
    iconUrl: 'https://cdn.simpleicons.org/react',
    iconName: 'Code2',
  },
  {
    id: 'Kj8L9wJuZYgL24zUlCN6',
    name: 'Git',
    level: 50,
    category: 'DevOps & Tools',
    iconUrl: 'https://cdn.simpleicons.org/git',
    iconName: 'GitBranch',
  },
  {
    id: 'S5o22lzsa5bk4l0M8OtK',
    name: 'Figma',
    level: 50,
    category: 'Design & Other',
    iconUrl: 'https://cdn.simpleicons.org/figma',
    iconName: 'Sparkles',
  },
  {
    id: 'xbQrjdyJWtwpjHeN5tnh',
    name: 'MySQL',
    level: 50,
    category: 'Database',
    iconUrl: 'https://cdn.simpleicons.org/mysql',
    iconName: 'Database',
  },
  {
    id: 'PROX6z8Heb95BgKR3Y3q',
    name: 'Mongo DB',
    level: 40,
    category: 'Database',
    iconUrl: 'https://cdn.simpleicons.org/mongodb',
    iconName: 'HardDrive',
  },
];

export const initialServices: ServiceItem[] = [
  {
    id: 'RrgOy6Bi0PLBFy3ZemhE',
    title: 'Telegram Bot',
    desc: 'Marketingni va biznes jarayonlarini avtomatlashtiruvchi, to\'lov tizimlari ulangan professional Telegram botlar.',
    priceRange: '150$ – 1500$',
    icon: 'Bot',
  },
  {
    id: 'uyS4ME3JcrrhBdRpA7vw',
    title: 'Landing Pagelar',
    desc: 'Sotuv do\'koni, brendlar yoki marketplace uchun yuqori konversiyali, tezkor va zamonaviy veb sahifalar.',
    priceRange: '20$ – 300$',
    icon: 'Code',
  },
];

export const initialSettings: UserSettings = {
  github: 'https://github.com/sanjarbek0828',
  telegram: 'https://t.me/sanjarbekdev',
  linkedin: 'https://www.linkedin.com/in/sanjarbek-otabekov-0600733bb/',
  email: 'sanjarbekotabekov010@gmail.com',
  resume: '/resume.pdf',
  aboutTitle: 'Men Haqimda',
  aboutShort: 'Zamonaviy veb-arxitektura va yuqori tezlikdagi raqamli mahsulotlar yaratishga ixtisoslashgan Full Stack muhandisman. Murakkab vazifalarga toza kod, ilg\'or texnologiyalar va intuitiv interfeyslar orqali qulay yechim topaman.',
  aboutFull: 'Mening maqsadim — har bir loyihada yuqori yuklanish tezligi, xavfsizlik va mukammal foydalanuvchi tajribasini (UX) ta\'minlash. Next.js, TypeScript va zamonaviy texnologiyalar bilan bizneslar uchun aniq natija beruvchi yechimlar yarataman.',
  expYears: '1+',
  githubCommits: '110+',
  githubYearText: 'Bu yilgi faollik',
  spotifySong: 'Lofi Programming Coding Playlist',
  spotifyArtist: 'Coding Playlist',
  instagram: '',
};

export const initialSiteContent: SiteContent = {
  hero: {
    name: 'Sanjarbek Otabekov',
    role: 'Full Stack Dasturchi',
    tagline: 'Tezkor, xavfsiz va zamonaviy raqamli tizimlar arxitekturasi',
    subtext: 'Next.js, TypeScript va zamonaviy veb texnologiyalar yordamida biznes va foydalanuvchilar uchun yuqori samaradorlikka ega raqamli mahsulotlar yarataman.',
    availabilityStatus: 'Loyihalar va frilans uchun ochiq',
    primaryCtaText: 'Loyihalarni ko‘rish',
    secondaryCtaText: 'Bog‘lanish',
    avatarUrl: '/personaj.png',
  },
  about: {
    heading: initialSettings.aboutTitle,
    bioParagraphs: [
      initialSettings.aboutShort,
      initialSettings.aboutFull
    ],
    yearsExperience: 1,
    projectsCompleted: 15,
    happyClients: 12,
    codeQualityRate: '99.9%',
    location: 'Toshkent, O‘zbekiston (Masofaviy ishga tayyor)',
    availability: 'Frilans & To‘liq bandlik',
    languages: ['O‘zbek tili (Ona tili)', 'Ingliz tili (Texnik/B2)', 'Rus tili (Muloqot)'],
    githubCommits: initialSettings.githubCommits,
    spotifySong: initialSettings.spotifySong,
    spotifyArtist: initialSettings.spotifyArtist,
  },
  skills: initialSkills,
  services: initialServices,
  settings: initialSettings,
};

export const initialMilestones: MilestoneItem[] = [
  {
    id: 'mile-1',
    period: '2026 — Hozir',
    title: 'Full Stack Muhandis & Veb Konsultant',
    organization: 'Mustaqil Frilans & Loyihalar',
    category: 'work',
    description: "Next.js 15, TypeScript va zamonaviy bulutli arxitektura orqali bizneslar uchun tezkor, xavfsiz va yuqori konversiyali raqamli tizimlar yaratish.",
    highlights: [
      "mebelmashhura.uz e-tijorat katalogini ishlab chiqib, 1 soniyadan tez yuklanishga erishildi",
      "Three.js va WebGL orqali 60 FPS silliq 3D Yer sayyorasi vizualizatsiyasi yaratildi",
      "Telegram savdo botlari, to'lov tizimlari (Click/Payme) va PWA ilovalari ishlab chiqildi"
    ],
    skills: ['Next.js 15', 'TypeScript', 'React 19', 'Tailwind CSS', 'Firebase', 'Three.js', 'Telegram API'],
    badge: 'Faol amaliyot'
  },
  {
    id: 'mile-2',
    period: '2025 — 2026',
    title: 'Meta Certified Full Stack & Frontend Muhandisligi',
    organization: 'Meta & Coursera Xalqaro Dasturi',
    category: 'education',
    description: "Meta tomonidan taqdim etilgan jahon andozalaridagi intensiv professional ixtisoslik. Chuqur frontend va backend tizimlari, xavfsiz RESTful APIlar va toza arxitektura.",
    highlights: [
      "Meta Full Stack Developer va Frontend Developer xalqaro maxsus sertifikatlariga ega bo'ldi",
      "Murakkab ma'lumotlar bazasi (PostgreSQL, MySQL) arxitekturasi va Django backend loyihalari",
      "Test-Driven Development (TDD) va CI/CD GitHub Actions avtomatlashtirish amaliyoti"
    ],
    skills: ['React', 'Node.js', 'Python', 'Django', 'PostgreSQL', 'Jest & TDD', 'APIs'],
    badge: 'Meta Akkreditatsiya'
  },
  {
    id: 'mile-3',
    period: '2025',
    title: 'Kiberxavfsizlik & Axborot Xavfsizligi Amaliyoti',
    organization: 'Pearson & Coursera',
    category: 'achievement',
    description: "Veb ilovalar va tarmoq infratuzilmasining xavfsizligini ta'minlash, penetratsion testlar o'tkazish hamda xakerlik tahdidlaridan himoyalanish metodologiyasi.",
    highlights: [
      "Certified Ethical Hacker (Pearson) va Cyber Security Leadership sertifikatlari",
      "OWASP Top 10 zaifliklarini bartaraf etish va mustahkam xavfsizlik qatlamlarini qurish",
      "Google Prompting Essentials va generativ AI vositalarini ishlab chiqish jarayoniga tatbiq etish"
    ],
    skills: ['Ethical Hacking', 'OWASP Top 10', 'Cyber Defense', 'Security Audits', 'Prompt Engineering'],
    badge: 'Certified Ethical Hacker'
  },
  {
    id: 'mile-4',
    period: '2024 — 2025',
    title: 'Dasturiy Ta\'minot Asoslari & Algoritmlar',
    organization: 'Amaliy Tadqiqot & Texnik Loyihalar',
    category: 'education',
    description: "Zamonaviy JavaScript (ES6+), ob'ektga yo'naltirilgan dasturlash (OOP), ma'lumotlar tuzilmalari va algoritmlar bo'yicha chuqur amaliy tajriba.",
    highlights: [
      "Git & GitHub Master Class (Packt) sertifikati va jamoaviy versiyalar boshqaruvi",
      "110+ dan ortiq real commitlar va open-source dasturiy ta'minot yaratish",
      "Algoritmik samaradorlik (Big-O) va brauzer render tezligini optimallashtirish"
    ],
    skills: ['JavaScript', 'HTML5 & CSS3', 'Git', 'Data Structures', 'Algorithms'],
    badge: 'Poydevor'
  }
];

export const initialTestimonials: TestimonialItem[] = [
  {
    id: 'test-1',
    name: 'Mashhura opa',
    role: "Do'kon Asoschisi",
    company: 'mebelmashhura.uz',
    comment: "Sanjarbek do'konimiz uchun yaratgan veb-sayt tufayli mijozlarimiz buyurtmalari sezilarli oshdi. Sayt telefonda ham chaqqon va bir zumda ochiladi, mebellarni ko'rish juda qulay. Mas'uliyatli va o'z ishining ustasi bo'lgan yosh mutaxassis!",
    rating: 5,
    projectTitle: "mebelmashhura.uz Web Sayti",
    verified: true
  },
  {
    id: 'test-2',
    name: 'Azizbek Rahimov',
    role: 'Startup Asoschisi & PM',
    company: 'Fintech Bot Solutions',
    comment: "Biznesimiz uchun Telegram savdo botini to'lov tizimlari (Click va Payme) hamda qulay admin boshqaruv paneli bilan tayyorlab berdi. 24/7 serverda barqaror ishlab turibdi. Eng asosiysi — belgilangan muddatdan avval topshirdi!",
    rating: 5,
    projectTitle: "Avtomatlashtirilgan Savdo Boti",
    verified: true
  },
  {
    id: 'test-3',
    name: 'Jamshid Alimov',
    role: 'Frontend Team Lead',
    company: 'Tech Innovators',
    comment: "Sanjarbek bilan bir necha loyihalarda hamkorlik qildik. Uning yozgan kodi toza, modulli va zamonaviy Next.js & TypeScript standartlariga to'liq mos keladi. Optimizatsiya va tezlikka bo'lgan e'tibori juda yuqori darajada.",
    rating: 5,
    projectTitle: "Next.js Web Arxitekturasi",
    verified: true
  }
];

